/* ACTIONS CONSTANTS */

export const CONSTANT = "CONSTANT";

export const DIALOG = "DIALOG";

export const MAPS_ACTIVE = "MAPS_ACTIVE";
export const MAPS_ADD = "MAPS_ADD";
export const MAPS_REMOVE = "MAPS_REMOVE";
export const MAPS_RENAME = "MAPS_RENAME";

export const ACTIVE_MAP_CHANGE = "ACTIVE_MAP_CHANGE";
export const ACTIVE_MAP_NODE_ADD = "ACTIVE_MAP_NODE_ADD";
export const ACTIVE_MAP_NODE_ACTIVE = "ACTIVE_MAP_NODE_ACTIVE";
export const ACTIVE_MAP_NODE_CHANGE = "ACTIVE_MAP_NODE_CHANGE";
export const ACTIVE_MAP_NODE_REMOVE = "ACTIVE_MAP_NODE_REMOVE";
export const ACTIVE_MAP_UNDO = "ACTIVE_MAP_UNDO";
export const ACTIVE_MAP_REDO = "ACTIVE_MAP_REDO";
export const ACTIVE_MAP_NODES_MOVE_DOWN = "ACTIVE_MAP_NODES_MOVE_DOWN";

/* OTHER CONSTANTS */

export const NEW_MAP_NAME = "Nová mapa";
export const NEW_NODE_TITLE = "Nový uzel";
export const MAP_SPACE_FACTOR = 10;